<?php

/**
 * @file
 * Contains the_entertainment_the_tvdb.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function the_entertainment_the_tvdb_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the the_entertainment_the_tvdb module.
    case 'help.page.the_entertainment_the_tvdb':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Find and populate metadata for TV series entities from The TVDB API') . '</p>';
      return $output;

    default:
  }
}
